name = "OMOPCommonDataModel"
uuid = "ba65db9e-6590-4054-ab8a-101ed9124986"
authors = ["Dilum Aluthge", "Brown Center for Biomedical Informatics", "JuliaHealth", "contributors"]
version = "0.1.4"

[deps]
InlineStrings = "842dd82b-1e85-43dc-bf29-5d0ee9dffc48"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[compat]
DataFrames = "0.21"
InlineStrings = "1.4"
PrettyPrint = "0.2"
Serialization = "1.11.0"
StructArrays = "0.4"
Tables = "1"
julia = "1.6"

[extras]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
PrettyPrint = "8162dcfd-2161-5ef2-ae6c-7681170c5f98"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["DataFrames", "Documenter", "PrettyPrint", "StructArrays", "Tables", "Test"]
